id: P007997
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:07.148793
source_metadata:
  id: bdr:W27509
  title: རྔོག་ལོ་ཙཱ་བ་བློ་ལྡན་ཤེས་རབ་ཀྱི་རྣམ་ཐར
  volume:
    2a1c8174cc5e459c9ae8d5b25b8d9f52:
      image_group_id: I5258
      title: ''
      volume_number: 1
      total_pages: 50
  author: ''
  volumes:
    ac8ab374f8f54b60a8ec355d8e3e3146:
      image_group_id: I5258
      title: ''
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
